### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by vladest** [sandsmark/slaq#2]
In order to have emoji support here is preliminary plan:
1. Once per day (week ?) read https://slackmojis.com content
2. Parse content and extract emojis and images url's
3. In separate worker download all the emojis to app's cache folder
4. use page update timestamp to see if its changed
5. Implement Custom Text element with emoji support

**Comment by sandsmark** [comment]
or https://gist.github.com/oliveratgithub/0bf11a9aff0d6da7b46f1490f86a71eb for the standard ones, https://api.slack.com/methods/emoji.list for the custom ones

**Comment by vladest** [comment]
implemented
