### ISSUE TITLE
Error: No message exists with the requested timestamp.

### ISSUE THREAD

**Issue by pillarsdotnet** [sandsmark/slaq#69]
When attempting to delete a message, slaq consistently fails with Slack error "No message exists with the requested timestamp."

**Comment by vladest** [comment]
Please check the fix now

**Comment by pillarsdotnet** [comment]
Ah; just pulled master; I see it.  Will rebuild and test shortly.

**Comment by pillarsdotnet** [comment]
Hmm.. Well, now it deletes the message, but it also crashes the client in the process.  Not sure how to grab a backtrace...

**Comment by pillarsdotnet** [comment]
Huh; worked fine when I deleted a newly-created message...

**Comment by pillarsdotnet** [comment]
And works fine when deleting some older messages.  Maybe the crash was unrelated.

Thanks for the fix!

**Comment by vladest** [comment]
hmm. probably need to introduce a crashpad sometime later
