### ISSUE TITLE
Streams threading support

### ISSUE THREAD

**Issue by vladest** [sandsmark/slaq#7]
Currently messages received and parsed in GUI thread which is creates bad UX
SlackStream class should be re implemented for using threads

**Comment by sandsmark** [comment]
if we can ensure it just interacts via signals and slots with the rest of the code, it should be as easy as basically calling «moveToThread(new QThread)» in the constructor.

**Comment by vladest** [comment]
yes, I assume so. Need to check that communication with GUI thread will be thru queued connections

**Comment by vladest** [comment]
implemented
