### ISSUE TITLE
Unknown module(s) in QT crash

### ISSUE THREAD

**Issue by Akiyamka** [sandsmark/slaq#76]
I understand absolutely nothing in qt development, so I apologize for the stupid question.
After install qt from web installer and clone repo i try build app and got crash
```
slaq on master
➜ qmake && make && ./slaq
Project ERROR: Unknown module(s) in QT: quick quickcontrols2 multimedia websockets quick-private qml-private quickcontrols2-private quicktemplates2-private qml
```
What i did wrong?

**Comment by vladest** [comment]
Hi

I suppose it is linux

I suggest you to be sure that you call qmake from freshly installed Qt (btw, what was the Qt version?)

**Comment by Akiyamka** [comment]
> I suppose it is linux
 Manjaro Linux x86_64 (4.19.13-1-MANJARO)

> what was the Qt version?
```
qmake -v
QMake version 3.1
Using Qt version 5.12.0 in /usr/lib
```

> I suggest you to be sure that you call qmake from freshly installed Qt
It looks like you're right, I already had qt on the system and qmake uses the wrong installation.

I'm looking for workarounds now
